Speed up stateindex and implement solvers for solving for MDP and QMDP solutions fastly
JuliaPOMDP/RockSample.jl pull request #10
Opened 2021-02-05 16:02 UTC by Wu-Chenyang

When using an MDP or QMDP solution as a heuristic in online planning, states need to be transformed into indexes with `stateindex` function. However, this function previously runs slow, because `LinearIndices` requires dynamic dispatch. I managed to speed it up but in an inelegant way. Is there a better way to do this?
Discrete value iteration requires several days to solve an MDP solution for RS(15,15), which is partly caused by the low efficiency of `stateindex`. I provided a DP algorithm for solving the optimal utility. Now the MDP solution for RS(15,15) can be solved in 10s.
In addition, a heuristic `RSExit` is provided, which is essentially the same as the fixed action policy `move east` but avoids senseless rollouts.

2021-02-05 23:33 UTC, zsunberg commented
Thanks! This looks good to me! @MaximeBouton do you have any comments?

One question: what does `rs_util` do? I'm assuming it calculates the value for the underlying MDP. If so, could you rename it to something that makes it more clear that it is the util for the fully observable mdp like `rs_mdp_util`? Also adding a short docstring would be helpful :)

2021-02-06 14:17 UTC, MaximeBouton commented
Taking a look right now!

2021-02-06 14:28 UTC, MaximeBouton requested changes

2021-02-06 14:28 UTC, MaximeBouton commented on src/RockSample.jl
> +function rsgen(map)
Could you document this function? It seems like it is generating a random instance of the rocksample problem. 
I have two comments: 
- add a docstring 
- maybe add an rng as an optional argument

2021-02-06 14:28 UTC, MaximeBouton commented on src/heuristics.jl
> +struct RSExitSolver <: Solver end
Please document this heuristic

2021-02-06 14:28 UTC, MaximeBouton commented on src/heuristics.jl
> +struct RSMDPSolver <: Solver
same here

2021-02-06 14:28 UTC, MaximeBouton commented on src/util.jl
> +function rs_util(m::RockSamplePOMDP)
what does this function do?

2021-02-06 14:28 UTC, MaximeBouton commented on src/RockSample.jl
> +function rsgen(map)
Actually, I am wondering if this function should not override the constructor rather: 
`RockSamplePOMDP(map, rng=GLOBAL_RNG)` instead of `rsgen`?

2021-02-06 14:30 UTC, MaximeBouton commented
Thank you for the contribution, the solution for speeding up the `stateindex` function looks fine. 
You added a lot of other features: heuristics, `rsgen`, `rsutil`. It would be nice to at least add docstrings for each of them. 
Also see my comment on potentially renaming `rsgen`.

2021-02-06 14:31 UTC, MaximeBouton commented
When I used this repo, I always used the SparseValueIteration solver which was rather fast, but of course now the conversion to a sparse tabular pomdp will be even faster ;).

2021-02-07 04:21 UTC, Wu-Chenyang commented
I've added some docstrings and renamed `rsgen` and `rs_util`. Is there something that is still not clear?

2021-02-07 04:25 UTC, Wu-Chenyang commented
On the SparseValueIteration, I should have known this before.😢 It is indeed significantly faster.

2021-02-12 05:10 UTC, zsunberg commented on src/heuristics.jl
> +# A fixed action policy which always takes the action `move east`.
```suggestion
"A fixed action policy which always takes the action `move east`."
```

2021-02-12 05:11 UTC, zsunberg commented on src/heuristics.jl
> +# Dedicated MDP solver for RockSample
```suggestion
"Dedicated MDP solver for RockSample"
```

2021-02-12 05:13 UTC, zsunberg commented
I think it looks good. Thanks again for the contribution! One note: It is better to use strings for documentation rather than comments because that can hook into the built in Julia help system or Documenter.jl. I made suggestions above.

@MaximeBouton I'll let you merge if you are satisfied.

2021-02-13 16:04 UTC, MaximeBouton commented
Looks great, I will merge

2021-02-13 16:05 UTC, merged

2021-02-15 12:30 UTC, Wu-Chenyang commented
I realized there is a mistake in [compat]. The version of `StaticArrays` can also be `0.12`.

2021-02-15 12:38 UTC, Wu-Chenyang commented
I thought it was me, but it wasn't. Maybe I should comment in #11 ?